{{- if .Values.nginx.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nextcloud.fullname" . }}-nginxconfig
  labels:
    {{- include "nextcloud.labels"  ( dict "rootContext" $ ) | nindent 4 }}
data:
  {{- if .Values.nginx.config.default }}
  default.conf: |-
    {{- tpl (.Files.Get "files/nginx.config.tpl") . | nindent 4 }}
  {{- end }}
  {{- with .Values.nginx.config.custom }}
  zz-custom.conf: |-
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
