postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password: "testing123456"

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  password: "testing123456"
