{{- if .Values.imaginary.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.fullname" . }}-imaginary
  labels:
    {{- include "nextcloud.labels"  ( dict "component" "imaginary"  "rootContext" $ ) | nindent 4 }}
    {{- with .Values.imaginary.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.imaginary.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.imaginary.service.type }}
  {{- with .Values.imaginary.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: http
      {{- with .Values.imaginary.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "nextcloud.selectorLabels"  ( dict "component" "imaginary"  "rootContext" $ ) | nindent 4 }}
{{- end }}
